### ISSUE TITLE
What version of Python do I need to run to get this to work?

### ISSUE THREAD

**Issue by ProfHariSeldon** [anoadragon453/Writing.com-Story-Scraper#2]
I have Python 2.7.14 (Release Date: Sept. 16, 2017)
I successfully installed:
pip install --upgrade mechanize
pip install --upgrade html2text
pip install --upgrade yattag
pip install --upgrade requests

But your python script throws errors when I try to login to writing.com, I assume because I am running a different version of Python than you used (you did write this 4 years ago not in 2017):

D:\Documents\writing\Archives\Writing.com-Story-Scraper-master>py writing-scraper.py
Starting login process...

Please enter a Writing.com username (Necessary for viewing Interactive Stories):
hariseldon

Enter password:
Password:
Attempting login...
Traceback (most recent call last):
  File "writing-scraper.py", line 171, in <module>
    login()
  File "writing-scraper.py", line 134, in login
    response = br.submit()
  File "C:\Python27\lib\site-packages\mechanize\_mechanize.py", line 684, in submit
    return self.open(self.click(*args, **kwds))
  File "C:\Python27\lib\site-packages\mechanize\_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "C:\Python27\lib\site-packages\mechanize\_mechanize.py", line 309, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 400: Bad Request

**Comment by anoadragon453** [comment]
This lib is super old so I'm not surprised if it's broken since. But the site itself doesn't look like its changed too much so I'll have a look at this and see if I can get it working again.

**Comment by ProfHariSeldon** [comment]
> This lib is super old so I'm not surprised if it's broken since. But the site itself doesn't look like its changed too much so I'll have a look at this and see if I can get it working again.

Thanks!  That would be great because I haven't found a Writing.com archiver that works even though I found two other options on GitHub (that don't work):
https://github.com/SolRacht/writing.com-archival
https://github.com/nononanon8/WritingInteractiveManager

**Comment by ProfHariSeldon** [comment]
Please also let me know if I can use a free Writing.com account with this script or I need to be a paid member, because:

Due to resource limitations, Interactive Stories are 
temporarily unavailable to visitors and free members.
Please try again in a few minutes... 
The first 4 chapters of a story are always available!
Note that constantly clicking reload to make this message disappear 
actually does the opposite, keeping server loads higher, for longer periods.
Paid members have no viewing or resource limitations!

**Comment by Ackater** [comment]
>https://github.com/SolRacht/writing.com-archival

Sorry to plug my own project here, but I found this issue while looking for a working one. Spent some time updating one of these programs to work. 

https://github.com/Ackater/writing.com-archival 

It's not 100%, but it works

**Comment by anoadragon453** [comment]
If it works we're happy to hear about it, thanks :)
